//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppFiscDF.infra.WebService.Email
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.anp.gov.br/componentes/mail/soap/rev1", ConfigurationName="AppFiscDF.infra.WebService.Email.MailWebService")]
    public interface MailWebService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseresponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(exception[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(check[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(role[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(contato[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(destinatario[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(parametro[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(cabecalho[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(anexo[]))]
        System.Threading.Tasks.Task<AppFiscDF.infra.WebService.Email.executardiagnosticoResponse> executardiagnosticoAsync(AppFiscDF.infra.WebService.Email.executardiagnostico request);
        
        [System.ServiceModel.OperationContractAttribute(Action="enviar-mensagem", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseresponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(exception[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(check[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(role[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(contato[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(destinatario[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(parametro[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(cabecalho[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(anexo[]))]
        System.Threading.Tasks.Task<AppFiscDF.infra.WebService.Email.enviarmensagemResponse> enviarmensagemAsync(AppFiscDF.infra.WebService.Email.enviarmensagem request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="diagnostics-response", Namespace="http://www.anp.gov.br/bibliotecas/webservices/rev1")]
    public partial class diagnosticsresponse : baseresponse
    {
        
        private diagnostics diagnosticsField;
        
        private role[] rolesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.anp.gov.br/common/diagnostics", Order=0)]
        public diagnostics diagnostics
        {
            get
            {
                return this.diagnosticsField;
            }
            set
            {
                this.diagnosticsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public role[] roles
        {
            get
            {
                return this.rolesField;
            }
            set
            {
                this.rolesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.anp.gov.br/common/diagnostics")]
    public partial class diagnostics
    {
        
        private check[] checksField;
        
        private string applicationversionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public check[] checks
        {
            get
            {
                return this.checksField;
            }
            set
            {
                this.checksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("application-version")]
        public string applicationversion
        {
            get
            {
                return this.applicationversionField;
            }
            set
            {
                this.applicationversionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.anp.gov.br/common/diagnostics")]
    public partial class check
    {
        
        private string nameField;
        
        private status statusField;
        
        private bool statusFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public status status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified
        {
            get
            {
                return this.statusFieldSpecified;
            }
            set
            {
                this.statusFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.anp.gov.br/common/diagnostics")]
    public enum status
    {
        
        /// <remarks/>
        SUCESSO,
        
        /// <remarks/>
        FALHA,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.anp.gov.br/componentes/mail/soap/rev1")]
    public partial class anexo
    {
        
        private byte[] conteudoField;
        
        private string nomeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=0)]
        public byte[] conteudo
        {
            get
            {
                return this.conteudoField;
            }
            set
            {
                this.conteudoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string nome
        {
            get
            {
                return this.nomeField;
            }
            set
            {
                this.nomeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.anp.gov.br/componentes/mail/soap/rev1")]
    public partial class cabecalho
    {
        
        private string nomeField;
        
        private string valorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string nome
        {
            get
            {
                return this.nomeField;
            }
            set
            {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string valor
        {
            get
            {
                return this.valorField;
            }
            set
            {
                this.valorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.anp.gov.br/componentes/mail/soap/rev1")]
    public partial class parametro
    {
        
        private string valorField;
        
        private string nomeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string valor
        {
            get
            {
                return this.valorField;
            }
            set
            {
                this.valorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string nome
        {
            get
            {
                return this.nomeField;
            }
            set
            {
                this.nomeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.anp.gov.br/componentes/mail/soap/rev1")]
    public partial class mensagem
    {
        
        private string assuntoField;
        
        private string conteudoField;
        
        private parametro[] parametrosField;
        
        private mailtemplate templateField;
        
        private tipomensagem tipoField;
        
        private bool tipoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string assunto
        {
            get
            {
                return this.assuntoField;
            }
            set
            {
                this.assuntoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string conteudo
        {
            get
            {
                return this.conteudoField;
            }
            set
            {
                this.conteudoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public parametro[] parametros
        {
            get
            {
                return this.parametrosField;
            }
            set
            {
                this.parametrosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public mailtemplate template
        {
            get
            {
                return this.templateField;
            }
            set
            {
                this.templateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public tipomensagem tipo
        {
            get
            {
                return this.tipoField;
            }
            set
            {
                this.tipoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoSpecified
        {
            get
            {
                return this.tipoFieldSpecified;
            }
            set
            {
                this.tipoFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="mail-template", Namespace="http://www.anp.gov.br/componentes/mail/soap/rev1")]
    public enum mailtemplate
    {
        
        /// <remarks/>
        PADRAO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="tipo-mensagem", Namespace="http://www.anp.gov.br/componentes/mail/soap/rev1")]
    public enum tipomensagem
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("TEMPLATE-CUSTOMIZADO")]
        TEMPLATECUSTOMIZADO,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("TEMPLATE-PRE-DEFINIDO")]
        TEMPLATEPREDEFINIDO,
        
        /// <remarks/>
        HTML,
        
        /// <remarks/>
        TEXTO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="configuracao-smtp", Namespace="http://www.anp.gov.br/componentes/mail/soap/rev1")]
    public partial class configuracaosmtp
    {
        
        private string hostField;
        
        private int portaField;
        
        private bool portaFieldSpecified;
        
        private string usuarioField;
        
        private string senhaField;
        
        private bool sslField;
        
        private string nomesessaojndiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string host
        {
            get
            {
                return this.hostField;
            }
            set
            {
                this.hostField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int porta
        {
            get
            {
                return this.portaField;
            }
            set
            {
                this.portaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool portaSpecified
        {
            get
            {
                return this.portaFieldSpecified;
            }
            set
            {
                this.portaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string usuario
        {
            get
            {
                return this.usuarioField;
            }
            set
            {
                this.usuarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string senha
        {
            get
            {
                return this.senhaField;
            }
            set
            {
                this.senhaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool ssl
        {
            get
            {
                return this.sslField;
            }
            set
            {
                this.sslField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("nome-sessao-jndi")]
        public string nomesessaojndi
        {
            get
            {
                return this.nomesessaojndiField;
            }
            set
            {
                this.nomesessaojndiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(destinatario))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.anp.gov.br/componentes/mail/soap/rev1")]
    public partial class contato
    {
        
        private string nomeField;
        
        private string emailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string nome
        {
            get
            {
                return this.nomeField;
            }
            set
            {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.anp.gov.br/componentes/mail/soap/rev1")]
    public partial class destinatario : contato
    {
        
        private tipodestinatario tipoField;
        
        private bool tipoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public tipodestinatario tipo
        {
            get
            {
                return this.tipoField;
            }
            set
            {
                this.tipoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoSpecified
        {
            get
            {
                return this.tipoFieldSpecified;
            }
            set
            {
                this.tipoFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="tipo-destinatario", Namespace="http://www.anp.gov.br/componentes/mail/soap/rev1")]
    public enum tipodestinatario
    {
        
        /// <remarks/>
        PUBLICO,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("COM-COPIA")]
        COMCOPIA,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("COM-COPIA-OCULTA")]
        COMCOPIAOCULTA,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.anp.gov.br/componentes/mail/soap/rev1")]
    public partial class email
    {
        
        private contato remetenteField;
        
        private configuracaosmtp configuracaoenvioField;
        
        private contato[] enderecosrespostaField;
        
        private destinatario[] destinatariosField;
        
        private mensagem mensagemField;
        
        private cabecalho[] cabecalhosField;
        
        private anexo[] anexosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public contato remetente
        {
            get
            {
                return this.remetenteField;
            }
            set
            {
                this.remetenteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("configuracao-envio", Order=1)]
        public configuracaosmtp configuracaoenvio
        {
            get
            {
                return this.configuracaoenvioField;
            }
            set
            {
                this.configuracaoenvioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("enderecos-resposta", Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public contato[] enderecosresposta
        {
            get
            {
                return this.enderecosrespostaField;
            }
            set
            {
                this.enderecosrespostaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public destinatario[] destinatarios
        {
            get
            {
                return this.destinatariosField;
            }
            set
            {
                this.destinatariosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public mensagem mensagem
        {
            get
            {
                return this.mensagemField;
            }
            set
            {
                this.mensagemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public cabecalho[] cabecalhos
        {
            get
            {
                return this.cabecalhosField;
            }
            set
            {
                this.cabecalhosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=6)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public anexo[] anexos
        {
            get
            {
                return this.anexosField;
            }
            set
            {
                this.anexosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.anp.gov.br/bibliotecas/webservices/rev1")]
    public partial class role
    {
        
        private string nameField;
        
        private bool haspermissionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("has-permission")]
        public bool haspermission
        {
            get
            {
                return this.haspermissionField;
            }
            set
            {
                this.haspermissionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.anp.gov.br/bibliotecas/webservices/rev1")]
    public partial class exception
    {
        
        private string messageField;
        
        private string detailField;
        
        private byte[] serializedexceptionField;
        
        private string keyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string detail
        {
            get
            {
                return this.detailField;
            }
            set
            {
                this.detailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("serialized-exception", DataType="base64Binary", Order=2)]
        public byte[] serializedexception
        {
            get
            {
                return this.serializedexceptionField;
            }
            set
            {
                this.serializedexceptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="exception-response", Namespace="http://www.anp.gov.br/bibliotecas/webservices/rev1")]
    public partial class exceptionresponse
    {
        
        private string messageField;
        
        private exception[] exceptionsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public exception[] exceptions
        {
            get
            {
                return this.exceptionsField;
            }
            set
            {
                this.exceptionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(diagnosticsresponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(messageResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="base-response", Namespace="http://www.anp.gov.br/bibliotecas/webservices/rev1")]
    public abstract partial class baseresponse
    {
        
        private exceptionresponse exceptionField;
        
        private responseStatus statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public exceptionresponse exception
        {
            get
            {
                return this.exceptionField;
            }
            set
            {
                this.exceptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public responseStatus status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.anp.gov.br/bibliotecas/webservices/rev1")]
    public enum responseStatus
    {
        
        /// <remarks/>
        SUCESSO,
        
        /// <remarks/>
        FALHA,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.anp.gov.br/componentes/mail/soap/rev1")]
    public partial class messageResponse : baseresponse
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="executar-diagnostico", WrapperNamespace="http://www.anp.gov.br/componentes/mail/soap/rev1", IsWrapped=true)]
    public partial class executardiagnostico
    {
        
        public executardiagnostico()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="diagnostico-response", WrapperNamespace="http://www.anp.gov.br/componentes/mail/soap/rev1", IsWrapped=true)]
    public partial class executardiagnosticoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.anp.gov.br/componentes/anp-cbcb/service/rev1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.anp.gov.br/componentes/anp-cbcb/service/rev1")]
        public AppFiscDF.infra.WebService.Email.diagnosticsresponse diagnostico;
        
        public executardiagnosticoResponse()
        {
        }
        
        public executardiagnosticoResponse(AppFiscDF.infra.WebService.Email.diagnosticsresponse diagnostico)
        {
            this.diagnostico = diagnostico;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="enviar-mensagem", WrapperNamespace="http://www.anp.gov.br/componentes/mail/soap/rev1", IsWrapped=true)]
    public partial class enviarmensagem
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.anp.gov.br/componentes/mail/soap/rev1", Order=0)]
        public AppFiscDF.infra.WebService.Email.email email;
        
        public enviarmensagem()
        {
        }
        
        public enviarmensagem(AppFiscDF.infra.WebService.Email.email email)
        {
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mail-response", WrapperNamespace="http://www.anp.gov.br/componentes/mail/soap/rev1", IsWrapped=true)]
    public partial class enviarmensagemResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.anp.gov.br/componentes/mail/soap/rev1", Order=0)]
        public AppFiscDF.infra.WebService.Email.messageResponse @return;
        
        public enviarmensagemResponse()
        {
        }
        
        public enviarmensagemResponse(AppFiscDF.infra.WebService.Email.messageResponse @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface MailWebServiceChannel : AppFiscDF.infra.WebService.Email.MailWebService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class MailWebServiceClient : System.ServiceModel.ClientBase<AppFiscDF.infra.WebService.Email.MailWebService>, AppFiscDF.infra.WebService.Email.MailWebService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public MailWebServiceClient() : 
                base(MailWebServiceClient.GetDefaultBinding(), MailWebServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.mail_service_port.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MailWebServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(MailWebServiceClient.GetBindingForEndpoint(endpointConfiguration), MailWebServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MailWebServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(MailWebServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MailWebServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(MailWebServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MailWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppFiscDF.infra.WebService.Email.executardiagnosticoResponse> AppFiscDF.infra.WebService.Email.MailWebService.executardiagnosticoAsync(AppFiscDF.infra.WebService.Email.executardiagnostico request)
        {
            return base.Channel.executardiagnosticoAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppFiscDF.infra.WebService.Email.executardiagnosticoResponse> executardiagnosticoAsync()
        {
            AppFiscDF.infra.WebService.Email.executardiagnostico inValue = new AppFiscDF.infra.WebService.Email.executardiagnostico();
            return ((AppFiscDF.infra.WebService.Email.MailWebService)(this)).executardiagnosticoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppFiscDF.infra.WebService.Email.enviarmensagemResponse> AppFiscDF.infra.WebService.Email.MailWebService.enviarmensagemAsync(AppFiscDF.infra.WebService.Email.enviarmensagem request)
        {
            return base.Channel.enviarmensagemAsync(request);
        }
        
        public async System.Threading.Tasks.Task<AppFiscDF.infra.WebService.Email.enviarmensagemResponse> enviarmensagemAsync(AppFiscDF.infra.WebService.Email.email email)
        {
            AppFiscDF.infra.WebService.Email.enviarmensagem inValue = new AppFiscDF.infra.WebService.Email.enviarmensagem();
            inValue.email = email;
            return await ((AppFiscDF.infra.WebService.Email.MailWebService)(this)).enviarmensagemAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.mail_service_port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.mail_service_port))
            {
                return new System.ServiceModel.EndpointAddress("http://as21ar000040zde.anp.net/mail-ws/mail-service/rev1");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return MailWebServiceClient.GetBindingForEndpoint(EndpointConfiguration.mail_service_port);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return MailWebServiceClient.GetEndpointAddress(EndpointConfiguration.mail_service_port);
        }
        
        public enum EndpointConfiguration
        {
            
            mail_service_port,
        }
    }
}
